name: Run Python Script

on:
  push:
    branches:
      - main  # Trigger the action on pushes to the "main" branch
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Check out the code from the repository

    - name: Set up Python
      uses: actions/setup-python@v4  # Set up Python environment
      with:
        python-version: 3.9  # Specify Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || true  # Skip if requirements.txt doesn't exist

    - name: Run Python Script
      run: python main.py
